<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_entrega_getpdf' => [[], ['_controller' => 'App\\Controller\\EntregaController::getPdf'], [], [['text', '/pdfdownload']], [], [], []],
    'app_entrega_login' => [[], ['_controller' => 'App\\Controller\\EntregaController::login'], [], [['text', '/']], [], [], []],
    'app_enviar' => [[], ['_controller' => 'App\\Controller\\EntregaController::enviar'], [], [['text', '/enviardatos']], [], [], []],
    'App\Controller\EntregaController::getPdf' => [[], ['_controller' => 'App\\Controller\\EntregaController::getPdf'], [], [['text', '/pdfdownload']], [], [], []],
    'App\Controller\EntregaController::login' => [[], ['_controller' => 'App\\Controller\\EntregaController::login'], [], [['text', '/']], [], [], []],
    'App\Controller\EntregaController::enviar' => [[], ['_controller' => 'App\\Controller\\EntregaController::enviar'], [], [['text', '/enviardatos']], [], [], []],
];
